version: '3'
services:
  jenkins:
    container_name: jenkins
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: jenkins-docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host("jenkins.12354.org")
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
    networks:
      - web
volumes:
  jenkins_home:
    external:
      name: jenkins_home
networks:
  web:
    external: true
